config/routes.rb
CortezLandscaping::Application.routes.draw do

  resources :landscapers


  devise_for :users, controllers: {sessions:'sessions', confirmations:'confirmations'}

  get 'admin' => 'administrative#index'
  get 'login_requests' => 'administrative#login_requests'
  get 'system_users' => 'administrative#system_users'
  post 'approve_login_request' => 'administrative#confirm_user'
  delete 'deny_login_request' => 'administrative#deny_user'
  post 'revoke_login' => 'administrative#revoke_login'
  delete 'destroy_user' => 'administrative#deny_user'

  resources :customer_properties
  post 'remove_ownership' => 'customer_properties#remove_ownership'

  resources :properties

  resources :states

  resources :countries

  resources :customers do
    resources :customer_addresses
  end

  resources :statuses

  resources :invoices

  resources :payment_details

  get 'calendar_data'   => 'events#to_calendar'
  post 'events_remove_from_invoice' => 'events#remove_from_invoice'
  post 'events_add_to_invoice' => 'events#add_to_invoice'
  resources :events do
    resources :event_services
  end

  resources :workorders do
    resources :workorder_services
    resources :events
    resources :invoices
    post 'close', on: :member
  end

  resources :services

  get 'services_data_tables_source' => 'services#data_tables_source'
  get 'states_data_tables_source' => 'states#data_tables_source'
  get 'payment_details_data_tables_source' => 'payment_details#data_tables_source'
  get 'unconfirmed_users_data_tables_source' => 'administrative#data_tables_source_unconfirmed'
  get 'confirmed_users_data_tables_source' => 'administrative#data_tables_source_confirmed'
  get 'properties_data_tables_source' => 'properties#data_tables_source'
  get 'properties_refresh_profile' => 'properties#refresh_profile'
  get 'properties_refresh_workorders' => 'properties#refresh_workorders'
  get 'properties_load_workorder_data' => 'properties#load_workorder_data'
  get 'properties_load_property_map_data' => 'properties#load_property_map_data'
  get 'customers_load_property_data' => 'customers#load_property_data'
  get 'customers_data_tables_source' => 'customers#data_tables_source'
  get 'customers_refresh_profile' => 'customers#refresh_profile'
  get 'customers_refresh_properties' => 'customers#refresh_properties'

  get 'landscapers_data_tables_source' => 'landscapers#data_tables_source'

  get 'refresh_profile' => 'properties#refresh_profile'

  get 'workorders_data_tables_source' => 'workorders#data_tables_source'

  get 'search' => 'application#search'
  get 'workorder_search' => 'application#workorder_search'
  get 'service_search' => 'application#service_search'
  get 'customer_search' => 'application#customer_search'
  get 'property_search' => 'application#property_search'
  get 'invoice_search' => 'application#invoice_search'

  get 'ajax_loader' => 'application#ajax_loader'

  get 'change_status' => 'application#change_status'

  get 'easter_egg' => 'application#easter_egg'

  root :to => "home#index"
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :status, primary_key: 'status_code', foreign_key: 'status_code'
  after_initialize :set_default_status
  has_many :payment_details, dependent: :destroy
  has_many :events
  has_many :workorders, through: :events

  scope :past_due, ->{where("due_date < '#{Date.today}' AND (status_code != '#{Status.get_code('Paid')}' OR status_code != '#{Status.get_code('Processing')}')")}
  scope :orphaned, ->{
    select { |i| i.empty? }
  }
  scope :not_orphaned, -> {select { |i| !i.empty? }}

  def invoice_amount_dollars
    if self.invoice_amount
      if self.invoice_amount.is_a?(Integer)
        return self.invoice_amount / 100.00
      elsif self.invoice_amount.is_a?(String)
        return ''
      end
    else
      return nil
    end
  end

  def invoice_amount_dollars=(amount)
    self.invoice_amount = (Float(amount) * 100).to_i
  rescue
    self.invoice_amount = amount
  end

  def set_default_status
    unless self.new_record?
      if past_due?
        set_past_due
      elsif created?
        set_created
      elsif paid?
        set_paid
      end
    end
  end

  def past_due?
    self.due_date < Date.today && self.balance_due > 0
  end

  def created?
    !self.past_due? && !paid?
  end

  def paid?
    self.balance_due == 0 && self.events.present? && self.payment_details.present?
  end

  def update_total
    p "Updating Invoice Total - #{events.map {|e| e.event_services.map(&:cost_dollars).sum}.sum}"
    self.invoice_amount_dollars = events.map {|e| e.event_services.map(&:cost_dollars).sum}.sum
    self.save
  end

  def finalize
    self.status_code = Status.get_code('Final')
    self.events.each(&:lock)
    self.save!
  end

  def destroy
    events.each(&:remove_from_invoice)
    super
  end

  def line_items
    event_services = events.map(&:event_services).flatten
    event_services.map do |es|
      {service: es.service.name, event_date:es.event.start, cost:es.cost}
    end
  end

  def payment_total
    payment_details.map do |payment|
      [payment.cash_subtotal_dollars.to_f, payment.check_subtotal_dollars.to_f, payment.cc_subtotal_dollars.to_f].sum
    end.flatten.sum
  end

  def make_payment(options={})
    payment_date = options.delete(:payment_date) || Date.today
    payment_type = options.delete(:payment_type)
    payment_amount = options.delete(:payment_amount)

    payment = PaymentDetail.new(invoice_id: id, payment_date: payment_date)
    case payment_type.upcase
      when 'CASH'
        payment.cash_subtotal_dollars = payment_amount
      when 'CREDIT'
        payment.cc_processing_code = options.delete(:processing_code)
        payment.cc_subtotal_dollars = payment_amount
      when 'CHECK'
        payment.check_name = options.delete(:check_name)
        payment.check_number = options.delete(:check_number)
        payment.check_routing = options.delete(:check_routing)
        payment.check_subtotal_dollars = payment_amount
    end

    payment.save

  end

  def unpaid?
    status_code != Status.get_code('Paid')
  end

  def balance_due
    invoice_amount_dollars - payment_total
  end

  def update_status
    if balance_due == 0 && events.present?
      set_paid
    elsif balance_due > 0 && due_date < Date.today
      set_past_due
    else
      set_created
    end

  end

  def workorder
    workorders.uniq.first
  end

  def empty?
    events.empty?
  end

  def self.destroy_orphaned
    orphaned.each(&:destroy)
  end


  private

  def set_paid
    unless self.status_code == Status.get_code('Paid')
      self.status_code = Status.get_code('Paid')
    end
  end

  def set_created
    unless self.status_code == Status.get_code('Created')
      self.status_code = Status.get_code('Created')
    end
  end

  def set_past_due
    unless self.status_code == Status.get_code('Past Due')
      self.status_code = Status.get_code('Past Due')
    end
  end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_filter :set_invoice, only: [:show, :edit, :update, :destroy]
  before_filter :set_workorder, only: [:index, :show, :new, :edit]

  # GET /invoices
  # GET /invoices.json
  def index
    if @workorder
      @invoices = Invoice.includes(:events).where("events.workorder_id = #{@workorder.id}")
    else
      @invoices = Invoice.all
    end
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    @property = @workorder.customer_property.property
    @customer = @workorder.customer_property.customer
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
    @invoice.id = Time.now.to_i
    @invoice.invoice_date = Date.today
    @invoice.due_date = Date.today + 1.month
    @invoice.save!
    @property = @workorder.customer_property.property
    @customer = @workorder.customer_property.customer
    redirect_to edit_invoice_path(id:@invoice.id, workorder_id:@workorder.id)
  end

  # GET /invoices/1/edit
  def edit
    @property = @workorder.customer_property.property
    @customer = @workorder.customer_property.customer
    respond_to do |format|
      format.html {
        unless @invoice.unpaid?
          redirect_to invoice_path(@invoice, workorder_id:@workorder.id)
        end
      }
    end
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render action: 'show', status: :created, location: @invoice }
      else
        format.html { render action: 'new' }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url }
      format.json { render json: {message:'Invoice was successfully deleted.'} }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    def set_workorder
      @workorder = Workorder.find(params[:workorder_id]) rescue nil
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:status_code, :invoice_date, :due_date, :invoice_amount, :balance_due)
    end
end

app/views/invoices/_form.html.haml
= form_for @invoice do |f|
  .row
    .col-md-3.well.noprint
      #past_events
        %table.table
          %caption.h4
            = 'Past Events'
            #add_all.h6= link_to 'Add All', '#'
          %thead
            %tr
              %th.h5= 'Date'
              %th.h5= 'Services'
              %th.h5= 'Cost'
              %th
          %tbody
            -if @workorder
              .invoice_id{style:'display:none'}= @invoice.id
              - @workorder.uninvoiced_events.past.order('start asc').each do |event|
                %tr
                  - event_services = event.event_services
                  %td.h6= event.start.strftime('%m/%d/%Y')
                  %td.h6= event_services.map(&:service).flatten.map(&:name).flatten.join(', ')
                  %td.h6= humanized_money_with_symbol(event_services.map(&:cost_dollars).sum)
                  %td
                    = content_tag(:i, nil, class:'glyphicon glyphicon-plus add-line-item', style:'color:green')
                    .event_id{style:'display:none'}= event.id

    .col-md-8.col-md-offset-1.well
      #invoice_document
        - if !@invoice.new_record?
          .row
            .col-md-12
              .pull-left
                = image_tag 'cortez_logo.png', size: '75x75'
              .h4.pull-right
                = "Invoice# #{@invoice.id}"
                .row
                  .col-md-12.noprint
                    = link_to 'Print', 'javascript:window.print()', class:'btn btn-xs btn-default'
                    = link_to 'Back', invoice_path(@invoice,workorder_id:@workorder.id), class:'btn btn-xs btn-default'

        - else
          .row
            .col-md-12
              = link_to 'Save Invoice', nil, class:'btn btn-lg btn-success'
        %hr
        .row
          .col-md-3.pull-left
            .h5= @customer.name
            .h5= @customer.customer_address.street_address_1
            .h5= @customer.customer_address.street_address_2
            .h5= "#{@customer.customer_address.city}, #{@customer.customer_address.state.short_name} #{@customer.customer_address.postal_code}"
            - if @customer.primary_phone
              .h5= @customer.primary_phone
            - elsif @customer.secondary_phone
              .h5= @customer.secondary_phone
            - if @customer.email
              .h5= @customer.email
          .col-md-3.col-md-offset-1.pull-left{style:'margin-left:100px;'}
            .h5
              %b Service Address
            .h5= @property.street_address_1
            - if @property.street_address_2
              .h5= @property.street_address_2
            .h5= "#{@property.city}, #{@property.state.short_name} #{@property.postal_code}"
          .col-md-3.pull-right
            .h5= "Created: #{(@invoice.invoice_date.strftime('%m/%d/%Y') rescue Date.today.strftime('%m/%d/%Y'))}"
            .h5= "Due By: #{(@invoice.due_date.strftime('%m/%d/%Y') rescue (Date.today+1.month).strftime('%m/%d/%Y'))}"
            .h5= "Total: #{humanized_money_with_symbol(@invoice.invoice_amount_dollars)}"
            .h5= "Balance: #{humanized_money_with_symbol(@invoice.balance_due)}"

        %hr
        .row
          .col-md-12
            %table.table.table-striped
              %thead
                %tr
                  %th.noprint
                  %th.h5= 'Date'
                  %th.h5= 'Services'
                  %th.h5= 'Comments'
                  %th.h5= 'Cost'
              %tbody
                - unless @invoice.events.empty?
                  - @invoice.events.order('start asc').each do |event|
                    = render 'line_item', {event:event}

        - unless @invoice.payment_details.empty?
          %hr
            .row
              .col-md-12
                %table.table.table-striped
                  %caption.h3 Payments Received
                  %thead
                    %tr
                      %th.h5= 'Date'
                      %th.h5= 'Received From'
                      %th.h5= 'Amount'
                      %th.h5= 'Payment Method'

                  %tbody
                    - @invoice.payment_details.order('payment_date asc').each do |payment|
                      = render 'payment_line', {payment:payment}

app/views/invoices/_line_item.html.haml
- event_services = event.event_services
%tr
  - unless controller_action == 'invoices#show'
    %td.h6.noprint
      = content_tag(:i, nil, class:'glyphicon glyphicon-remove remove-line-item', style:'color:red')
      .event_id{style:'display:none'}= event.id
  %td.h6= event.start.strftime('%m/%d/%Y')
  %td.h6= event_services.map(&:service).flatten.map(&:name).flatten.join(', ')
  %td.h6= event.comment
  %td.h6= humanized_money_with_symbol(event_services.map(&:cost_dollars).sum)

app/views/invoices/_payment_line.html.haml
%tr
  %td.h6= payment.payment_date.strftime('%m/%d/%Y')
  %td.h6= payment.name
  %td.h6= humanized_money_with_symbol(payment.amount)
  %td.h6= payment.payment_method
  %td.h6
    - if payment.check_number.present?
      = payment.check_number
    - else
      –
  %td.h6
    - if payment.check_routing.present?
      = payment.check_routing
    - else
      –
  %td.h6
    - if payment.cc_processing_code.present?
      = payment.cc_processing_code
    - else
      –

app/views/invoices/edit.html.haml
= render 'form'

app/views/invoices/index.html.haml
%table.table
  %caption.h4
    %center
      Invoices
      - unless @workorder.locked? || !@workorder.uninvoiced_events.past.present?
        = link_to content_tag(:i, nil, {class:'glyphicon glyphicon-plus pull-right', style:'color:green'}), new_invoice_path(workorder_id:@workorder.id), target:'_blank'
  %thead
    %tr
      %th.h5 Number
      %th.h5 Due By
      %th.h5 Balance
      %th.h5 Status
      %th
  %tbody
    - @invoices.each do |invoice|
      %tr
        %td.h6= link_to invoice.id, invoice_path(invoice, workorder_id:@workorder.id), target:'_blank'
        %td.h6= invoice.due_date
        %td.h6= humanized_money_with_symbol(invoice.balance_due)
        %td.h6{style:"color:#{invoice.past_due? ? 'red' : 'black'}"}
          = invoice.status.status
        %td
          - disabled = (invoice.status.status != 'Paid') ? false : true
          =link_to 'Payment', new_payment_detail_path(invoice_id:invoice.id), remote:true, id:'new_payment_detail_link', class:'btn btn-xs btn-success', style:'margin-right: 5px;', disabled:disabled
          - unless @workorder.locked?
            =link_to 'Delete', invoice_path(invoice), remote:true, id:'delete_invoice_link', :method => :delete, :data => { :confirm => 'Are you sure?', type: :json}, class:'btn btn-xs btn-danger'

%br

= link_to 'New Invoice', new_invoice_path

app/views/invoices/new.html.haml
= render 'form'

app/views/invoices/show.html.haml
.row
  .col-md-8.col-md-offset-2.well
    - if !@invoice.new_record?
      .row
        #header.col-md-12
          .col-md-4.pull-left
            = image_tag 'cortez_logo.png', size: '75x75'
          .col-md-4.h3
            #invoice_paid= 'PAID' unless @invoice.unpaid?
          .col-md-4.h4.pull-right
            = "Invoice# #{@invoice.id}"
            .row
              .col-md-12.noprint
                = link_to 'Print', 'javascript:window.print()', class:'btn btn-xs btn-default'
                - if @invoice.unpaid?
                  = link_to 'Edit', edit_invoice_path(@invoice, workorder_id:@workorder.id), class:'btn btn-xs btn-default'

    - else
      .row
        .col-md-12
          = link_to 'Save Invoice', nil, class:'btn btn-lg btn-success'
    %hr
    .row
      .col-md-3.pull-left
        .h5= @customer.name
        .h5= @customer.customer_address.street_address_1
        .h5= @customer.customer_address.street_address_2
        .h5= "#{@customer.customer_address.city}, #{@customer.customer_address.state.short_name} #{@customer.customer_address.postal_code}"
        - if @customer.primary_phone
          .h5= @customer.primary_phone
        - elsif @customer.secondary_phone
          .h5= @customer.secondary_phone
        - if @customer.email
          .h5= @customer.email
      .col-md-3.col-md-offset-1.pull-left{style:'margin-left:100px;'}
        .h5
          %b Service Address
        .h5.noprint= @property.html_full_address
        .h5.onlyprint{style:'margin-top:0px;'}
          .h5= @property.street_address_1
          .h5= @property.street_address_2
          .h5= "#{@property.city}, #{@property.state.short_name} #{@property.postal_code}"
      .col-md-3.pull-right
        .h5= "Created: #{(@invoice.invoice_date.strftime('%m/%d/%Y') rescue Date.today.strftime('%m/%d/%Y'))}"
        .h5= "Due By: #{(@invoice.due_date.strftime('%m/%d/%Y') rescue (Date.today+1.month).strftime('%m/%d/%Y'))}"
        .h5= "Total: #{humanized_money_with_symbol(@invoice.invoice_amount_dollars)}"
        .h5= "Balance: #{humanized_money_with_symbol(@invoice.balance_due)}"

    %hr
    .row
      .col-md-12
        %table.table.table-striped
          %thead
            %tr
              %th.h5= 'Date'
              %th.h5= 'Services'
              %th.h5= 'Comments'
              %th.h5= 'Cost'
          %tbody
            - unless @invoice.events.empty?
              - @invoice.events.order('start asc').each do |event|
                = render 'line_item', event:event

    - unless @invoice.payment_details.empty?
      %hr
        .row
          .col-md-12
            %table.table.table-striped
              %caption.h3 Payments Received
              %thead
                %tr
                  %th.h5= 'Date'
                  %th.h5= 'Received From'
                  %th.h5= 'Amount'
                  %th.h5= 'Payment Method'
                  %th.h5= 'Check Number'
                  %th.h5= 'Routing Number'
                  %th.h5= 'Processing Code'

              %tbody
                - @invoice.payment_details.order('payment_date asc').each do |payment|
                  = render 'payment_line', {payment:payment}