config/routes.rb
CortezLandscaping::Application.routes.draw do

  resources :landscapers


  devise_for :users, controllers: {sessions:'sessions', confirmations:'confirmations'}

  get 'admin' => 'administrative#index'
  get 'login_requests' => 'administrative#login_requests'
  get 'system_users' => 'administrative#system_users'
  post 'approve_login_request' => 'administrative#confirm_user'
  delete 'deny_login_request' => 'administrative#deny_user'
  post 'revoke_login' => 'administrative#revoke_login'
  delete 'destroy_user' => 'administrative#deny_user'

  resources :customer_properties
  post 'remove_ownership' => 'customer_properties#remove_ownership'

  resources :properties

  resources :states

  resources :countries

  resources :customers do
    resources :customer_addresses
  end

  resources :statuses

  resources :invoices

  resources :payment_details

  get 'calendar_data'   => 'events#to_calendar'
  post 'events_remove_from_invoice' => 'events#remove_from_invoice'
  post 'events_add_to_invoice' => 'events#add_to_invoice'
  resources :events do
    resources :event_services
  end

  resources :workorders do
    resources :workorder_services
    resources :events
    resources :invoices
    post 'close', on: :member
  end

  resources :services

  get 'services_data_tables_source' => 'services#data_tables_source'
  get 'states_data_tables_source' => 'states#data_tables_source'
  get 'payment_details_data_tables_source' => 'payment_details#data_tables_source'
  get 'unconfirmed_users_data_tables_source' => 'administrative#data_tables_source_unconfirmed'
  get 'confirmed_users_data_tables_source' => 'administrative#data_tables_source_confirmed'
  get 'properties_data_tables_source' => 'properties#data_tables_source'
  get 'properties_refresh_profile' => 'properties#refresh_profile'
  get 'properties_refresh_workorders' => 'properties#refresh_workorders'
  get 'properties_load_workorder_data' => 'properties#load_workorder_data'
  get 'properties_load_property_map_data' => 'properties#load_property_map_data'
  get 'customers_load_property_data' => 'customers#load_property_data'
  get 'customers_data_tables_source' => 'customers#data_tables_source'
  get 'customers_refresh_profile' => 'customers#refresh_profile'
  get 'customers_refresh_properties' => 'customers#refresh_properties'

  get 'landscapers_data_tables_source' => 'landscapers#data_tables_source'

  get 'refresh_profile' => 'properties#refresh_profile'

  get 'workorders_data_tables_source' => 'workorders#data_tables_source'

  get 'search' => 'application#search'
  get 'workorder_search' => 'application#workorder_search'
  get 'service_search' => 'application#service_search'
  get 'customer_search' => 'application#customer_search'
  get 'property_search' => 'application#property_search'
  get 'invoice_search' => 'application#invoice_search'

  get 'ajax_loader' => 'application#ajax_loader'

  get 'change_status' => 'application#change_status'

  get 'easter_egg' => 'application#easter_egg'

  root :to => "home#index"
end

app/models/workorder.rb
class Workorder < ActiveRecord::Base
  after_create :set_default_status
  after_initialize :set_default_status
  after_commit :update_workorder_services, :update_events, on: :update
  require 'model_locking'
  include ModelLocking
  include ActionView::Helpers::UrlHelper
  include MoneyRails::ActionViewExtension

  belongs_to :status, primary_key: 'status_code', foreign_key: 'status_code'
  has_many :events, dependent: :destroy
  has_many :invoices, through: :events
  has_many :workorder_services, dependent: :destroy
  has_many :services, through: :workorder_services
  accepts_nested_attributes_for :workorder_services, allow_destroy: true
  belongs_to :customer_property

  scope :created, ->{where(status_code: Status.get_code('Created'))}
  scope :active, ->{where(status_code: Status.get_code('Active'))}
  scope :on_hold, ->{where(status_code: Status.get_code('Locked'))}
  scope :closed, ->{where(status_code: Status.get_code('Closed'))}
  scope :current, ->{where("status_code != #{Status.get_code('Closed')}")}

  #validates_associated :workorder_services
  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :start_date

  def set_default_status
    unless self.new_record? || self.closed?
      if !customer_property.locked?
          self.start_date <= Date.today ? self.change_status('Active') : self.change_status('Created')
      end
    end
  end

  def closed?
    self.status_code == Status.get_code('Closed')
  end

  def future_events
    events.future_events
  end

  def future_uninvoiced_events
    future_events.not_invoiced
  end

  def destroy_future_uninvoiced_events
    #event.destroy will update the invoice for us
    future_uninvoiced_events.each(&:destroy)
  end

  def update_events
    destroy_future_uninvoiced_events
    create_events(true)
  end

  def billing_cycle_events
    events.billing_cycle
  end

  def uninvoiced_events
    events.not_invoiced
  end

  def uninvoiced_billing_cycle_events
    billing_cycle_events & uninvoiced_events
  end

  def valid_uninvoiced_billing_cycle_events
    Event.billing_cycle.not_invoiced.past.where(workorder_id: self.id)
  end

  def has_valid_uninvoiced_billing_cycle_events
    valid_uninvoiced_billing_cycle_events.count > 0
  end

  def has_uninvoiced_events_in_past
    Event.not_invoiced.before_billing_cycle.where(workorder_id: self.id).count > 0
  end

  def close
    self.generate_invoice(uninvoiced_events.past)
    self.status_code = Status.get_code('Closed')
    self.save
    self.destroy_future_uninvoiced_events
  end

  def generate_invoice(invoice_events=valid_uninvoiced_billing_cycle_events)
    invoice = Invoice.new
    invoice.id = Time.now.to_i
    invoice_events.each do |event|
      event.invoice_id = invoice.id
      if event.make_invoiced && event.save
        invoice.invoice_amount += event.event_services.map(&:cost).sum
      end
    end

    if invoice_events.any?
      invoice.invoice_date = Date.today
      invoice.due_date = Date.today + 1.month
      invoice.save if invoice.valid?
    end
  end

  def invoices
    if invoice_ids.uniq.length > 0
      Invoice.where("id IN (#{invoice_ids.uniq.join(', ')})")
    end
  end

  def property
    customer_property.try(:property)
  end

  def to_data_table_row
    [name, customer_property.property.html_full_address, customer_property.customer.html_name, next_event || 'N/A', status.status, humanized_money_with_symbol(balance_due)]
  end

  def html_name
    link_to name, Rails.application.routes.url_helpers.workorder_path(self)
  end

  def next_event
    event = future_events.first
    if event
      event.event_services.map(&:service).map(&:name).join(', ') << event.start.strftime(' on %Y-%m-%d')
    end
  end

  def balance_due
    if invoices
      invoices.map(&:balance_due).sum
    else
      0
    end
  end

  def change_status(status)
    unless status_code == Status.get_code(status)
      self.status_code = Status.get_code(status)
      self.save
      case status
        when 'Locked'
          events.not_invoiced.map(&:lock)
        when 'Active', 'Created'
          events.not_invoiced.map(&:unlock)
      end
    end
  end

  def self.generate_all_invoices
    p "#{Time.now} - Generating invoices for all workorders..."
    all.each(&:generate_invoice)
    p "#{Time.now} - Complete!"
  end

  def self.create_all_events
    p "#{Time.now} - Generating scheduled events for billing cycle..."
    ModelLocking.not_locked(self).map(&:workorder_services).each(&:create_events)
    p "#{Time.now} - Complete!"
  end

  private

  def update_workorder_services
    self.workorder_services.each(&:update_events)
  end

  def update_events
    self.events.each {|e| e.name = self.name; e.save}
  end
end

app/controllers/workorders_controller.rb
class WorkordersController < ApplicationController
  before_filter :set_workorder, only: [:show, :edit, :update, :destroy, :close]
  before_filter :set_customer_property, only: [:new, :edit, :create, :update]

  # GET /workorders
  # GET /workorders.json
  def index
    @workorders = Workorder.all
  end

  # GET /workorders/1
  # GET /workorders/1.json
  def show
  end

  # GET /workorders/new
  def new
    @workorder = Workorder.new
    respond_to do |format|
      format.html {
        unless params[:customer_property_id]
          redirect_to :back rescue redirect_to properties_path
        end
      }
      format.js
    end
  end

  # GET /workorders/1/edit
  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /workorders
  # POST /workorders.json
  def create
    @workorder = Workorder.new(workorder_params)
    respond_to do |format|
      if @workorder.save
        format.html { redirect_to @workorder, notice: 'Work Order was successfully created.' }
        format.json { render json: {message:'Work Order successfully created!', id:@customer_property.property.id}, status: :created }
        format.js   { render json: {message:'Work Order successfully created!', id:@customer_property.property.id}, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @workorder.errors, status: :unprocessable_entity }
        format.js   { render json: @workorder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workorders/1
  # PATCH/PUT /workorders/1.json
  def update
    respond_to do |format|
      if @workorder.update_attributes(workorder_params)
        format.html { redirect_to @workorder, notice: 'Workorder was successfully updated.' }
        format.json { render json: {message:'Work Order successfully updated!', id:@customer_property.property.id}, status: :created }
        format.js   { render json: {message:'Work Order successfully updated!', id:@customer_property.property.id}, status: :created }
      else
        format.html { render action: 'edit' }
        format.json { render json: @workorder.errors, status: :unprocessable_entity }
        format.js   { render json: @workorder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workorders/1
  # DELETE /workorders/1.json
  def destroy
    @workorder.destroy
    respond_to do |format|
      format.html { redirect_to workorders_url }
      format.json { head :no_content }
    end
  end

  def close
    if @workorder.close
      respond_to do |format|
        format.json {render json: {message:'Work Order Closed.'}}
      end
    else
      respond_to do |format|
        format.json {render json: {message:'Failed To Close Work Order.'}}
      end
    end
  end

  def data_tables_source
    @workorders = Workorder.all
    respond_to do |format|
      format.js {render json: {aaData:@workorders.map(&:to_data_table_row)}}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workorder
      @workorder = Workorder.find(params[:id])
    end

    def set_customer_property
      @customer_property = CustomerProperty.find(params[:customer_property_id] || workorder_params[:customer_property_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workorder_params
      params.require(:workorder).permit(:status_code, :name, :start_date, :customer_property_id, workorder_services_attributes:[:id, :service_id, :cost, :cost_dollars, :schedule, :single_occurrence_date, :_destroy])
    end
end

app/views/workorders/_form.html.haml
-case controller_action
  -when 'workorders#new'
    -id='new_workorder'
    -submit_text='Create Work Order'
  -when 'workorders#edit'
    -id='edit_workorder'
    -submit_text='Update Work Order'

= nested_form_for @workorder, remote:true, :html => {id:id, :class => 'form-vertical', :'data-type' => :json} do |f|
  = f.hidden_field :customer_property_id, value: @customer_property.id
  .row{style:'height: 350px; overflow-y:scroll; overflow-x:hidden;'}
    %fieldset.col-md-6
      %legend.h4 Work Order Information
      .col-md-12.workorder-name
        = f.text_field :name, placeholder: 'Name', class:'form-control'
      .col-md-6.workorder-start
        -disabled = @workorder.start_date < Date.today rescue false
        = f.text_field :start_date, placeholder:'Start Date', class:'form-control datepicker', autocomplete:'off', disabled:disabled
      .col-md-12
        = f.submit submit_text, class:'btn btn-md btn-success'
    %fieldset.col-md-6
      %legend.h4 Services
      .col-md-12
        = f.fields_for :workorder_services do |ws|
          = render partial: 'shared/service_fields', locals:{f:ws, service:ws.object.service}
        = f.link_to_add 'Add A New Service', :workorder_services, class:'btn btn-sm btn-default'
= javascript_include_tag 'workorders'

app/views/workorders/_list.html.haml
%table#workorders.table.table-hover.datatable
  %tr
    %thead
      %th.h5= 'Name'
      %th.h5= 'Property'
      %th.h5= 'Customer'
      %th.h5= 'Next Billing Cycle Event'
      %th.h5= 'Status'
      %th.h5= 'Balance Due'
  %tr
    %tbody

app/views/workorders/edit.html.haml
- model_class = Workorder
.row
  .page-header
    %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/workorders/edit.js.haml
:plain
  $(document).ready(function(){
    $('#ajax-modal .modal-body').html("#{ j render partial:'form' }")
    $('#ajax-modal').modal('show')
  })

app/views/workorders/index.html.haml
.row
  .col-md-12.well
    = render 'list'

app/views/workorders/new.html.haml
- model_class = Workorder
.row
  .page-header
    %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/workorders/new.js.haml
:plain
  $(document).ready(function(){
    $('#ajax-modal .modal-body').html("#{ j render partial:'form' }")
    $('#ajax-modal').modal('show')
  })

app/views/workorders/show.html.haml
- model_class = Workorder
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @workorder.name + ' - ' + @workorder.status.status

%p
  %strong= model_class.human_attribute_name(:start_date) + ':'
  %br
  = @workorder.start_date

%p
  %strong Upcoming Events:
  %br
  - @workorder.workorder_services.each do |ws|
    = "#{ws.service.name} - #{ws.converted_schedule.next_occurrence.strftime('%m/%d/%Y') rescue 'N/A'}"
    %br

- if @workorder.services.any?
  %h5.page-header Services
  .row
    .span12
      %table.table.table-striped
        %tr
          %th Service
          %th Cost
          %th Schedule
        - @workorder.workorder_services.each do |ws|
          %tr
            %td= ws.service.name
            %td= humanized_money_with_symbol(ws.cost)
            %td= ws.converted_schedule
- else
  %h5.page-header No Services


.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), workorders_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_workorder_path(@workorder), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), workorder_path(@workorder), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'