config/routes.rb
CortezLandscaping::Application.routes.draw do

  resources :landscapers


  devise_for :users, controllers: {sessions:'sessions', confirmations:'confirmations'}

  get 'admin' => 'administrative#index'
  get 'login_requests' => 'administrative#login_requests'
  get 'system_users' => 'administrative#system_users'
  post 'approve_login_request' => 'administrative#confirm_user'
  delete 'deny_login_request' => 'administrative#deny_user'
  post 'revoke_login' => 'administrative#revoke_login'
  delete 'destroy_user' => 'administrative#deny_user'

  resources :customer_properties
  post 'remove_ownership' => 'customer_properties#remove_ownership'

  resources :properties

  resources :states

  resources :countries

  resources :customers do
    resources :customer_addresses
  end

  resources :statuses

  resources :invoices

  resources :payment_details

  get 'calendar_data'   => 'events#to_calendar'
  post 'events_remove_from_invoice' => 'events#remove_from_invoice'
  post 'events_add_to_invoice' => 'events#add_to_invoice'
  resources :events do
    resources :event_services
  end

  resources :workorders do
    resources :workorder_services
    resources :events
    resources :invoices
    post 'close', on: :member
  end

  resources :services

  get 'services_data_tables_source' => 'services#data_tables_source'
  get 'states_data_tables_source' => 'states#data_tables_source'
  get 'payment_details_data_tables_source' => 'payment_details#data_tables_source'
  get 'unconfirmed_users_data_tables_source' => 'administrative#data_tables_source_unconfirmed'
  get 'confirmed_users_data_tables_source' => 'administrative#data_tables_source_confirmed'
  get 'properties_data_tables_source' => 'properties#data_tables_source'
  get 'properties_refresh_profile' => 'properties#refresh_profile'
  get 'properties_refresh_workorders' => 'properties#refresh_workorders'
  get 'properties_load_workorder_data' => 'properties#load_workorder_data'
  get 'properties_load_property_map_data' => 'properties#load_property_map_data'
  get 'customers_load_property_data' => 'customers#load_property_data'
  get 'customers_data_tables_source' => 'customers#data_tables_source'
  get 'customers_refresh_profile' => 'customers#refresh_profile'
  get 'customers_refresh_properties' => 'customers#refresh_properties'

  get 'landscapers_data_tables_source' => 'landscapers#data_tables_source'

  get 'refresh_profile' => 'properties#refresh_profile'

  get 'workorders_data_tables_source' => 'workorders#data_tables_source'

  get 'search' => 'application#search'
  get 'workorder_search' => 'application#workorder_search'
  get 'service_search' => 'application#service_search'
  get 'customer_search' => 'application#customer_search'
  get 'property_search' => 'application#property_search'
  get 'invoice_search' => 'application#invoice_search'

  get 'ajax_loader' => 'application#ajax_loader'

  get 'change_status' => 'application#change_status'

  get 'easter_egg' => 'application#easter_egg'

  root :to => "home#index"
end

app/models/workorder_service.rb
class WorkorderService < ActiveRecord::Base
  after_create :create_events
  after_update :update_events
  after_destroy :delete_event_services
  include IceCube
  require 'date_helper'
  include DateHelper

  belongs_to :service
  belongs_to :workorder
  has_many :event_services

  serialize :schedule, Hash
  validates_presence_of :schedule
  validates_presence_of :cost
  validates_numericality_of :cost

  def cost_dollars
    if self.cost
      if self.cost.is_a?(Integer)
        return self.cost / 100.00
      elsif self.cost.is_a?(String)
        return ''
      end
    else
      return nil
    end
  end

  def cost_dollars=(amount)
    self.cost = (Float(amount) * 100.00).ceil
  rescue
    self.cost = amount
  end

  def create_events
    occurrence_dates = self.recurring? ?
       get_requested_occurrences(false) :
       [self.single_occurrence_date.to_datetime.midnight]

    process_occurrence_dates(occurrence_dates)
  end

  def update_events
    occurrence_dates = self.recurring? ?
        get_requested_occurrences(true) :
        [self.single_occurrence_date.to_datetime.midnight]

    process_occurrence_dates(occurrence_dates)
    destroy_invalid_events unless self.single_occurrence?
  end

  def process_occurrence_dates(occurrence_dates)
    occurrence_dates.each do |event_date|
      event = Event.where("workorder_id = #{self.workorder_id} AND start::date = '#{event_date}'").first_or_initialize
      if event.new_record?
        event = create_event(event_date)
      end
      create_event_service(event)
    end
  end

  def get_requested_occurrences(future_only)
    if future_only
      get_remaining_occurrence_dates
    else
      get_all_occurrence_dates
    end
  end

  def get_all_occurrence_dates
    converted_schedule.all_occurrences.map(&:to_date)
  end

  def get_remaining_occurrence_dates
    if converted_schedule.present?
      dates = converted_schedule.remaining_occurrences.map(&:to_date)
      if get_all_occurrence_dates.include? Date.today
        dates << Date.today unless dates.include? Date.today
      end
      dates
    else
      []
    end
  end

  def create_event(event_date)
    event = Event.new
    event.workorder_id = self.workorder_id
    event.start = event_date
    event.end = nil
    event.all_day = true
    event.name = self.workorder.name
    event.invoice_id = nil
    event.status_code = Status.get_code('Not Invoiced')
    Event.create!(event.attributes)
  end

  def create_event_service(event)
    event_service = EventService.new
    event_service.workorder_service_id = self.id
    event_service.event_id = event.id
    event_service.service_id = self.service_id
    event_service.cost_dollars = self.cost_dollars

    p "EVENT ID = #{event.id}"
    p "CHECKING IF EVENT SERVICE FOR #{service.name} EXISTS IN EVENT ALREADY"
    if EventService.where(event_id:event.id, service_id:self.service_id).empty?
      unless event_service.workorder_service_id.nil? || event.invoiced?
        p "EVENT SERVICE NOT FOUND FOR EVENT #{event.id} - #{service.name}"
        EventService.create!(event_service.attributes)
      end
    else
      event_service = EventService.where(event_id:event.id, service_id:self.service_id).first
      p "EVENT SERVICE FOUND FOR EVENT #{event.id} - #{service.name}"
      #check for price difference
      unless self.cost == event_service.cost
        event_service.cost = self.cost
        event_service.save
      end
    end
    p '*******************************'
  end

  def single_occurrence?
    single_occurrence_date.present?
  end

  def recurring?
    schedule.present?
  end

  def future_events
    Event.future_events.where(workorder_id:self.workorder_id)
  end

  def destroy_invalid_events
    remaining_dates = future_events.map(&:start).map(&:to_date)
    p "REMAINING DATES = #{remaining_dates.sort}"
    valid_dates = get_remaining_occurrence_dates
    p "VALID DATES = #{valid_dates.sort}"
    to_destroy = remaining_dates - valid_dates
    p "TO DESTROY = #{to_destroy}"
    to_destroy.each do |event_date|
      event = Event.where("workorder_id = #{self.workorder_id} AND start::date = '#{event_date}'").first
      if event.present?
        event.destroy
      end
    end
  end

  def schedule=(new_schedule)
    if new_schedule != 'null' && new_schedule.present?
      write_attribute(:schedule, RecurringSelect.dirty_hash_to_rule(new_schedule).to_hash)
    else
      nil
    end
  end

  def converted_schedule
    s = read_attribute(:schedule)
    unless s.empty?
      cycle_start = billing_cycle_start
      cycle_end   = billing_cycle_end
      the_schedule = Schedule.new(cycle_start)
      the_schedule.add_recurrence_rule(RecurringSelect.dirty_hash_to_rule(s).until(cycle_end))
      the_schedule
    end
  end

  def billing_cycle_start
    #check to see if there are any invoices
    #if not then the workorder is starting in the middle of a cycle
    #if so then all recurring workorders will start the billing cycle on the first
    workorder.invoices.present? ? DateHelper.first_day_of_month : workorder.start_date
  end

  def billing_cycle_end
    #if the billing cycle starts in a future month, then set the end date to the last day of the starting month
    DateHelper.last_day_of_month(billing_cycle_start.year, billing_cycle_start.month)
  end

  def delete_event_services
    if self.event_services
      if self.single_occurrence?
        self.event_services.each(&:destroy)
      else
        self.event_services.each do |event_service|
          if event_service.event.start > DateTime.now
            if event_service.event.event_services.count == 0
              event_service.event.destroy
            else
              event_service.destroy
            end
          end
        end
      end
    end
  end
end

app/controllers/workorder_services_controller.rb
class WorkorderServicesController < ApplicationController
  before_filter :set_workorder
  before_filter :set_workorder_service, only: [:show, :edit, :update, :destroy]

  # GET /workorder_services
  # GET /workorder_services.json
  def index
    @workorder_services = WorkorderService.where( workorder_id: params[:workorder_id] )
  end

  # GET /workorder_services/1
  # GET /workorder_services/1.json
  def show
  end

  # GET /workorder_services/new
  def new
    @workorder_service = WorkorderService.new
  end

  # GET /workorder_services/1/edit
  def edit
  end

  # POST /workorder_services
  # POST /workorder_services.json
  def create
    @workorder_service = WorkorderService.new(workorder_service_params)
    respond_to do |format|
      if @workorder_service.save
        format.html { redirect_to workorder_workorder_service_path(@workorder, @workorder_service), notice: 'Workorder service was successfully created.' }
        format.json { render json: {message:'Service Has Been Added To Work Order!'}, status: :created, location: workorder_workorder_service_path(@workorder, @workorder_service) }
      else
        format.html { render action: 'new' }
        format.json { render json: @workorder_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workorder_services/1
  # PATCH/PUT /workorder_services/1.json
  def update
    respond_to do |format|
      if @workorder_service.update_attributes(workorder_service_params)
        format.html { redirect_to @workorder_service, notice: 'Work Order Service Has Been Successfully Updated' }
        format.json { render json: {message: 'Work Order Service Has Been Successfully Updated!'} }
      else
        format.html { render action: 'edit' }
        format.json { render json: @workorder_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workorder_services/1
  # DELETE /workorder_services/1.json
  def destroy
    @workorder_service.destroy
    respond_to do |format|
      format.html { redirect_to workorder_workorder_services_url }
      format.json { head :no_content }
      format.js   { render json: {message: 'Work Order Service Has Been Deleted!'}, status: :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workorder_service
      @workorder_service = WorkorderService.find(params[:id])
    end

    def set_workorder
      @workorder = Workorder.find(params[:workorder_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workorder_service_params
      params.require(:workorder_service).permit(:service_id, :workorder_id, :schedule, :cost, :cost_dollars, :single_occurrence_date)
    end
end

app/views/workorder_services/_form.html.haml
- case controller_action
  - when 'workorder_services#new'
    - form_method = :post
    - url = "/workorders/#{@workorder.id}/workorder_services"
    - submit_button_text = 'Add New Service'
    - id = 'new_workorder_service'
  - when 'workorder_services#edit'
    - form_method = :put
    - url = "/workorders/#{@workorder.id}/workorder_services/#{@workorder_service.id}"
    - submit_button_text = 'Edit This Service'
    - id = 'edit_workorder_service'

= nested_form_for([:workorder, @workorder_service], url:url,
                                                   html: {method:form_method,
                                                              id: id,
                                                           class:'form-vertical',
                                                            data:{remote:true, type: :json}}) do |f|
  .row
    .col-md-12
      .form-inputs
        - service = @workorder_service.new_record? ? nil : @workorder_service.service
        = render 'shared/service_fields', {f:f, service:service, unique:(unique rescue nil)}
        = f.hidden_field :workorder_id, {value:@workorder.id}
  .row
    .col-md-offset-1.col-md-10
      .form-actions
        = f.button submit_button_text, {class:'btn btn-block btn-success submit'}
        = link_to 'Cancel', '#', class:'btn btn-block btn-default cancel'

app/views/workorder_services/edit.html.haml
%h1 Editing workorder_service

#form
  - unique= Time.now.to_i
  - single= @workorder_service.schedule.empty?
  - date = @workorder_service.single_occurrence_date.strftime('%Y-%m-%d') rescue nil
  = render 'form', {unique:unique}
  :coffee
    $(document).ready ->

      unique_suffix = "#{unique}"
      $("#single_occurrence_" + unique_suffix).val("").datepicker datepicker_defaults()
      $("#service_toggle_" + unique_suffix + " label.btn").on "click", ->
        selected_button_id = $(this).children("input[type='radio']").attr("id")
        display_element = $("div[class~='" + selected_button_id + "_" + unique_suffix + "']")
        $(".toggle_group_" + unique_suffix + ":not([class~='" + $(display_element).attr("class") + "']").fadeOut complete: ->
          display_element.delay(600).fadeIn()
          display_element.find("input:first").focus()
          if selected_button_id is "recurring-service"
            setTimeout (->
              $("#single_occurrence_" + unique_suffix).val ""
            ), 500

      if #{single}
        $('#single-service').click()
        $("[id*='single_occurrence']").val("#{date}")

= link_to 'Show', workorder_workorder_service_path(@workorder)
\|
= link_to 'Back', workorder_workorder_services_path

app/views/workorder_services/index.html.haml
%h1 Listing workorder_services

%table
  %tr
    %th Service
    %th Workorder
    %th Schedule
    %th Cost
    %th
    %th
    %th

  - @workorder_services.each do |workorder_service|
    %tr
      %td= workorder_service.service
      %td= workorder_service.workorder
      %td= workorder_service.schedule
      %td= workorder_service.cost
      %td= link_to 'Show', workorder_workorder_service_path(@workorder, workorder_service)
      %td= link_to 'Edit', edit_workorder_workorder_service_path(@workorder, workorder_service)
      %td= link_to 'Destroy', workorder_workorder_service_path(@workorder, workorder_service), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Workorder service', new_workorder_workorder_service_path

app/views/workorder_services/new.html.haml
%h1 New workorder_service

#form
  - unique= Time.now.to_i
  = render 'form', {unique:unique}
  :coffee
    $(document).ready ->
      unique_suffix = "#{unique}"

      $("#single_occurrence_" + unique_suffix).val("").datepicker datepicker_defaults()
      $("#service_toggle_" + unique_suffix + " label.btn").on "click", ->
        selected_button_id = $(this).children("input[type='radio']").attr("id")
        display_element = $("div[class~='" + selected_button_id + "_" + unique_suffix + "']")
        $(".toggle_group_" + unique_suffix + ":not([class~='" + $(display_element).attr("class") + "']").fadeOut complete: ->
          display_element.delay(600).fadeIn()
          display_element.find("input:first").focus()
          if selected_button_id is "recurring-service"
            setTimeout (->
              $("#single_occurrence_" + unique_suffix).val ""
            ), 500

= link_to 'Back', workorder_workorder_services_path

app/views/workorder_services/show.html.haml
%p#notice= notice

%p
  %b Service:
  = @workorder_service.service
%p
  %b Workorder:
  = @workorder_service.workorder
%p
  %b Schedule:
  = @workorder_service.schedule
%p
  %b Cost:
  = @workorder_service.cost

= link_to 'Edit', edit_workorder_workorder_service_path(@workorder,@workorder_service)
\|
= link_to 'Back', workorder_workorder_services_path