config/routes.rb
CortezLandscaping::Application.routes.draw do

  resources :landscapers


  devise_for :users, controllers: {sessions:'sessions', confirmations:'confirmations'}

  get 'admin' => 'administrative#index'
  get 'login_requests' => 'administrative#login_requests'
  get 'system_users' => 'administrative#system_users'
  post 'approve_login_request' => 'administrative#confirm_user'
  delete 'deny_login_request' => 'administrative#deny_user'
  post 'revoke_login' => 'administrative#revoke_login'
  delete 'destroy_user' => 'administrative#deny_user'

  resources :customer_properties
  post 'remove_ownership' => 'customer_properties#remove_ownership'

  resources :properties

  resources :states

  resources :countries

  resources :customers do
    resources :customer_addresses
  end

  resources :statuses

  resources :invoices

  resources :payment_details

  get 'calendar_data'   => 'events#to_calendar'
  post 'events_remove_from_invoice' => 'events#remove_from_invoice'
  post 'events_add_to_invoice' => 'events#add_to_invoice'
  resources :events do
    resources :event_services
  end

  resources :workorders do
    resources :workorder_services
    resources :events
    resources :invoices
    post 'close', on: :member
  end

  resources :services

  get 'services_data_tables_source' => 'services#data_tables_source'
  get 'states_data_tables_source' => 'states#data_tables_source'
  get 'payment_details_data_tables_source' => 'payment_details#data_tables_source'
  get 'unconfirmed_users_data_tables_source' => 'administrative#data_tables_source_unconfirmed'
  get 'confirmed_users_data_tables_source' => 'administrative#data_tables_source_confirmed'
  get 'properties_data_tables_source' => 'properties#data_tables_source'
  get 'properties_refresh_profile' => 'properties#refresh_profile'
  get 'properties_refresh_workorders' => 'properties#refresh_workorders'
  get 'properties_load_workorder_data' => 'properties#load_workorder_data'
  get 'properties_load_property_map_data' => 'properties#load_property_map_data'
  get 'customers_load_property_data' => 'customers#load_property_data'
  get 'customers_data_tables_source' => 'customers#data_tables_source'
  get 'customers_refresh_profile' => 'customers#refresh_profile'
  get 'customers_refresh_properties' => 'customers#refresh_properties'

  get 'landscapers_data_tables_source' => 'landscapers#data_tables_source'

  get 'refresh_profile' => 'properties#refresh_profile'

  get 'workorders_data_tables_source' => 'workorders#data_tables_source'

  get 'search' => 'application#search'
  get 'workorder_search' => 'application#workorder_search'
  get 'service_search' => 'application#service_search'
  get 'customer_search' => 'application#customer_search'
  get 'property_search' => 'application#property_search'
  get 'invoice_search' => 'application#invoice_search'

  get 'ajax_loader' => 'application#ajax_loader'

  get 'change_status' => 'application#change_status'

  get 'easter_egg' => 'application#easter_egg'

  root :to => "home#index"
end

app/controllers/administrative_controller.rb
class AdministrativeController < ApplicationController
  def index
  end

  def login_requests
    render template: 'administrative/login_requests'
  end

  def system_users
    render template: 'administrative/system_users'
  end

  def confirm_user
    respond_to do |format|
      format.js {
        user = User.find params[:user_id]
        user.admin_confirm(current_user)
        render json:{message:"#{user.email} is now allowed to login"}, status: :ok
      }
    end
  end

  def revoke_login
    respond_to do |format|
      format.js {
        user = User.find params[:user_id]
        user.revoke_login(current_user)
        render json:{message:"#{user.email} login privileges have been revoked."}, status: :ok
      }
    end
  end

  def deny_user
    respond_to do |format|
      format.js {
        user = User.find params[:user_id]
        user.deny_login(current_user)
        render json:{message:"#{user.email} has been removed from the system."}, status: :ok
      }
    end
  end

  def data_tables_source_unconfirmed
    @users = User.unconfirmed
    respond_to do |format|
      format.js {render json: {aaData:@users.map(&:to_data_table_row_unconfirmed)}}
    end
  end

  def data_tables_source_confirmed
    @users = User.confirmed
    respond_to do |format|
      user_data = @users.map do |user|
        user.to_data_table_row_confirmed(current_user)
      end
      format.js {render json: {aaData:user_data}}
    end
  end

end

app/views/administrative/index.html.haml
.row.well
  #sidebar.col-md-3
    .btn-group-vertical
    = link_to 'Landscapers',      landscapers_path,     remote:true, class:'btn btn-default btn-lg btn-block', id:'admin_landscapers_link'
    = link_to 'Services',         services_path,        remote:true, class:'btn btn-default btn-lg btn-block', id:'admin_services_link'
    = link_to 'States',           states_path,          remote:true, class:'btn btn-default btn-lg btn-block', id:'admin_states_link'
    = link_to 'Payments',         payment_details_path, remote:true, class:'btn btn-default btn-lg btn-block', id:'admin_payments_link'
    = link_to 'Authorized Users', system_users_path,    remote:true, class:'btn btn-default btn-lg btn-block', id:'admin_users_link'
    = link_to 'Login Requests',   login_requests_path,  remote:true, class:'btn btn-default btn-lg btn-block', id:'admin_login_requests_link'
  .col-md-9
    #admin_content_area

app/views/administrative/login_requests.html.haml
#table_data{style:'margin-top:20px;'}
  %table.table.datatable
    %thead
      %tr
        %th.h5 Email
        %th.h5 Request Date
        %th.h5
        %th.h5
    %tbody

app/views/administrative/system_users.html.haml
#table_data{style:'margin-top:20px;'}
  %table.table.datatable
    %thead
      %tr
        %th.h5 Email
        %th.h5 Confirmation Date
        %th.h5
        %th.h5
    %tbody